name: Render Quarto paper

# Grant write access for push events to commit PDF back
permissions:
  contents: write

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      # 1 – checkout with persist-credentials for push events
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      # 2 – install Quarto + TinyTeX
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # 3 – render PDF
      - name: Render PDF
        working-directory: paper
        run: make paper

      # 4 – move the PDF up one level
      - name: Move PDF into paper/
        run: mv paper/_build/paper.pdf paper/paper.pdf

      # 5 – commit & push rendered PDF
      - name: Commit & push rendered PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add paper/paper.pdf
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: update rendered paper.pdf"
            git push origin "${{ github.ref_name }}"
          else
            echo "🚫 No changes to commit"
          fi

      # 6 – always upload as artifact for easy download (works on PRs too)
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
