name: Render Quarto paper

on:
  push:
    branches: ["main"]        # rebuild when main changes
  pull_request:               # and on every PR

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    # 1 – check out your sources
    - uses: actions/checkout@v4

    # 2 – install Quarto + TinyTeX in one shot
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true            # install TinyTeX (enough for most papers)
        # cache: true            # uncomment to cache TinyTeX between runs

    # 3 – render just the paper (other .qmd stay untouched)
    - name: Render PDF
      working-directory: paper
      run: |
        make paper

    # 4 – upload the artefact so you can grab it from the “Actions” tab
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: paper
        path: paper/paper.pdf
